// Claude Code CLI profile engine. Parallels macos.rs (Desktop), but isolates the
// *CLI*: a per-profile CLAUDE_CONFIG_DIR plus a per-profile OAuth token injected
// via CLAUDE_CODE_OAUTH_TOKEN (which overrides the shared macOS Keychain slot).
use serde::Serialize;

#[derive(Serialize, Clone)]
pub struct CliProfile {
    pub name: String,
    pub slug: String,
    pub config_dir: String,   // CLAUDE_CONFIG_DIR for this profile
    pub launcher_path: String, // the generated .command
    pub has_token: bool,       // a token is stored in the Keychain for this slug
    pub account_email: Option<String>, // parsed from <config_dir>/.claude.json if present
    pub data_size: String,
    pub created: Option<u64>,
    pub last_active: Option<u64>,
}

pub const KEYCHAIN_PREFIX: &str = "com.claudeprofiles.cli";

/// Escape a string for safe interpolation inside a double-quoted bash string.
pub fn sh_dq_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(c, '"' | '\\' | '$' | '`') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// The bash body of a profile launcher. Reads the token from the Keychain at run
/// time (never bakes it into the file) and execs the real claude CLI.
/// Precondition: `slug` must be pre-slugified ([a-z0-9-], via platform::slugify) — it is interpolated raw into the Keychain service/account strings.
pub fn render_launcher(name: &str, slug: &str, config_dir: &str, claude_bin: &str) -> String {
    let name_e = sh_dq_escape(name);
    let cfg_e = sh_dq_escape(config_dir);
    let bin_e = sh_dq_escape(claude_bin);
    let svc = format!("{KEYCHAIN_PREFIX}.{slug}");
    format!(
        "#!/bin/bash\n\
         # Generated by Claude Profiles — CLI account launcher for \"{name_e}\".\n\
         export CLAUDE_CONFIG_DIR=\"{cfg_e}\"\n\
         TOKEN=\"$(security find-generic-password -w -s \"{svc}\" -a \"{slug}\" 2>/dev/null)\"\n\
         if [ -z \"$TOKEN\" ]; then\n\
         \x20 echo \"No saved token for profile \\\"{name_e}\\\".\"\n\
         \x20 echo \"Open Claude Profiles and use \\\"Set token\\\" for this profile.\"\n\
         \x20 exit 1\n\
         fi\n\
         export CLAUDE_CODE_OAUTH_TOKEN=\"$TOKEN\"\n\
         CLAUDE_BIN=\"{bin_e}\"\n\
         [ -x \"$CLAUDE_BIN\" ] || CLAUDE_BIN=\"$(command -v claude)\"\n\
         exec \"$CLAUDE_BIN\" \"$@\"\n"
    )
}

/// Extract a usable token from whatever the user pasted (a bare token, or the
/// full `claude setup-token` output). Prefer an sk-ant-* token; else last line.
pub fn parse_setup_token_output(raw: &str) -> Option<String> {
    for tok in raw.split_whitespace() {
        if tok.starts_with("sk-ant-") && tok.len() > 12 {
            return Some(tok.to_string());
        }
    }
    raw.lines()
        .rev()
        .map(|l| l.trim())
        .find(|l| !l.is_empty())
        .map(|s| s.to_string())
}

/// Cheap extract of oauthAccount.emailAddress from a .claude.json body without
/// pulling in serde_json.
pub fn extract_email(json: &str) -> Option<String> {
    let key = "\"emailAddress\"";
    let i = json.find(key)? + key.len();
    let rest = &json[i..];
    let start = rest.find('"')? + 1;
    let after = &rest[start..];
    let end = after.find('"')?;
    let email = &after[..end];
    if email.contains('@') { Some(email.to_string()) } else { None }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launcher_has_config_dir_token_and_exec() {
        let s = render_launcher("Work", "work", "/tmp/cfg dir", "/opt/homebrew/bin/claude");
        assert!(s.contains("export CLAUDE_CONFIG_DIR=\"/tmp/cfg dir\""));
        assert!(s.contains("com.claudeprofiles.cli.work"));
        assert!(s.contains("export CLAUDE_CODE_OAUTH_TOKEN=\"$TOKEN\""));
        assert!(s.trim_end().ends_with("exec \"$CLAUDE_BIN\" \"$@\""));
    }

    #[test]
    fn launcher_escapes_quotes_in_name() {
        let s = render_launcher("Ac\"me", "acme", "/tmp/x", "/bin/claude");
        assert!(s.contains("Ac\\\"me"));
    }

    #[test]
    fn escapes_shell_metacharacters() {
        // The point of the escaper: neutralize $, backtick, ", \ inside a double-quoted bash string.
        assert_eq!(sh_dq_escape("a\"b"), "a\\\"b");
        assert_eq!(sh_dq_escape("a\\b"), "a\\\\b");
        assert_eq!(sh_dq_escape("$(whoami)"), "\\$(whoami)");
        assert_eq!(sh_dq_escape("`id`"), "\\`id\\`");
    }

    #[test]
    fn parse_prefers_sk_ant_token() {
        let raw = "Some banner\nYour token:\nsk-ant-oat01-ABCDEF123456\nDone.";
        assert_eq!(parse_setup_token_output(raw).as_deref(), Some("sk-ant-oat01-ABCDEF123456"));
    }

    #[test]
    fn parse_falls_back_to_last_line() {
        assert_eq!(parse_setup_token_output("  \n  hello-token  \n\n").as_deref(), Some("hello-token"));
    }

    #[test]
    fn parse_empty_is_none() {
        assert_eq!(parse_setup_token_output("   \n  "), None);
    }

    #[test]
    fn extract_email_works() {
        let j = r#"{"userID":"x","oauthAccount":{"emailAddress":"a@b.com","org":"y"}}"#;
        assert_eq!(extract_email(j).as_deref(), Some("a@b.com"));
        assert_eq!(extract_email(r#"{"no":"email"}"#), None);
    }
}
