// Claude Code CLI profile engine. Parallels macos.rs (Desktop), but isolates the
// *CLI*: each profile is a real Claude login, seeded by a one-time `/login`
// inside its own CLAUDE_CONFIG_DIR. Claude Code itself namespaces the OAuth
// credential in the macOS Keychain by a hash of CLAUDE_CONFIG_DIR (service
// `Claude Code-credentials-<sha256(config_dir)[:8]>`), so distinct config dirs
// give distinct, durable, concurrently-usable logins — with zero app-managed
// secrets. No token injection, no shim, no setup-token capture.
use serde::Serialize;
use std::path::{Path, PathBuf};

#[derive(Serialize, Clone)]
pub struct CliProfile {
    pub name: String,
    pub slug: String,
    pub config_dir: String,    // CLAUDE_CONFIG_DIR for this profile
    pub launcher_path: String, // the generated .command
    pub logged_in: bool,       // an oauthAccount exists in <config_dir>/.claude.json
    pub account_email: Option<String>, // parsed from <config_dir>/.claude.json if present
    pub data_size: String,
    pub created: Option<u64>,
    pub last_active: Option<u64>,
}

/// Escape a string for safe interpolation inside a double-quoted bash string.
pub fn sh_dq_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(c, '"' | '\\' | '$' | '`') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// Wrap a string as a safe POSIX single-quoted shell word (handles embedded ').
pub fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// The bash body of a profile launcher. Sets the profile's CLAUDE_CONFIG_DIR and
/// execs the real claude CLI — claude resolves the per-profile login from its
/// own Keychain slot (namespaced by config dir). On first run claude shows the
/// login prompt; that one-time /login seeds the profile.
pub fn render_launcher(name: &str, config_dir: &str, claude_bin: &str) -> String {
    let name_e = sh_dq_escape(name);
    let cfg_e = sh_dq_escape(config_dir);
    let bin_e = sh_dq_escape(claude_bin);
    format!(
        "#!/bin/bash\n\
         # Generated by Claude Profiles — CLI account launcher for \"{name_e}\".\n\
         export CLAUDE_CONFIG_DIR=\"{cfg_e}\"\n\
         CLAUDE_BIN=\"{bin_e}\"\n\
         [ -x \"$CLAUDE_BIN\" ] || CLAUDE_BIN=\"$(command -v claude)\"\n\
         exec \"$CLAUDE_BIN\" \"$@\"\n"
    )
}

/// The Keychain service name claude uses for a login stored under `config_dir`
/// (namespaced by config-dir hash). Pure + testable — verified against a real
/// profile this session (see test).
pub fn login_keychain_service_for_dir(config_dir: &str) -> String {
    use sha2::{Digest, Sha256};
    let h = Sha256::digest(config_dir.as_bytes());
    let hex: String = h.iter().take(4).map(|b| format!("{b:02x}")).collect(); // first 8 hex chars
    format!("Claude Code-credentials-{hex}")
}

/// Cheap extract of oauthAccount.emailAddress from a .claude.json body without
/// pulling in serde_json.
pub fn extract_email(json: &str) -> Option<String> {
    let key = "\"emailAddress\"";
    let i = json.find(key)? + key.len();
    let rest = &json[i..];
    let start = rest.find('"')? + 1;
    let after = &rest[start..];
    let end = after.find('"')?;
    let email = &after[..end];
    if email.contains('@') { Some(email.to_string()) } else { None }
}

// ---- cross-platform Windows-launcher builders (pure; unit-tested on macOS) --

/// Double `%` so it is literal inside a batch `set "VAR=…"`. NOT a
/// general-purpose escaper: it is sufficient only for the constrained values we
/// pass (config-dir paths under `%APPDATA%` with `[a-z0-9-]` slugs, and the
/// resolved claude bin path). Within `set "…"` the other cmd metachars
/// (`& ^ < > |`) are already literal, so `%` is the only hazard for those inputs.
#[allow(dead_code)] // used on Windows + in tests; unreferenced in the macOS build
pub fn cmd_set_value_escape(s: &str) -> String { s.replace('%', "%%") }

/// Path, relative to the npm global bin dir (where the `claude` shim lives), of
/// the native `claude.exe` that `@anthropic-ai/claude-code` unpacks for
/// win32-x64. Last-resort resolver fallback: a Windows field report found the
/// npm `.ps1` shim can carry a broken path, and a Tauri GUI may not inherit the
/// shell PATH (so `where claude` misses). Pure + unit-tested on macOS.
#[allow(dead_code)] // used on Windows + in tests; unreferenced in the macOS build
pub fn nested_win_claude_exe(npm_bin_dir: &Path) -> PathBuf {
    npm_bin_dir
        .join("node_modules").join("@anthropic-ai").join("claude-code")
        .join("node_modules").join("@anthropic-ai").join("claude-code-win32-x64")
        .join("claude.exe")
}

/// Sanitize a display name for a batch `REM` comment: strip CR/LF (which would
/// end the comment line) and double `%`.
#[allow(dead_code)] // used on Windows + in tests; unreferenced in the macOS build
fn cmd_comment_sanitize(s: &str) -> String {
    s.chars()
        .filter(|c| *c != '\r' && *c != '\n')
        .collect::<String>()
        .replace('%', "%%")
}

/// Windows `.cmd` launcher: set this account's CLAUDE_CONFIG_DIR, then `call`
/// the real claude (`call`, because claude is usually a `.cmd` shim; without
/// `call` control would not return to this script). CRLF line endings for cmd.
#[allow(dead_code)] // used on Windows + in tests; unreferenced in the macOS build
pub fn render_launcher_win(name: &str, config_dir: &str, claude_bin: &str) -> String {
    let name_c = cmd_comment_sanitize(name);
    let cfg = cmd_set_value_escape(config_dir);
    let bin = cmd_set_value_escape(claude_bin);
    // Parity with the macOS launcher: fall back to PATH `claude` if the baked
    // path is stale (Claude moved/updated), so the launcher self-heals.
    format!(
        "@echo off\r\n\
         REM Generated by Personae — CLI account launcher for \"{name_c}\".\r\n\
         set \"CLAUDE_CONFIG_DIR={cfg}\"\r\n\
         set \"CLAUDE_BIN={bin}\"\r\n\
         if not exist \"%CLAUDE_BIN%\" set \"CLAUDE_BIN=claude\"\r\n\
         call \"%CLAUDE_BIN%\" %*\r\n"
    )
}

/// One-shot interactive sign-in window: set env, run `claude auth login`,
/// keep the console open so the user sees the result.
#[allow(dead_code)] // used on Windows + in tests; unreferenced in the macOS build
pub fn render_login_win(name: &str, config_dir: &str, claude_bin: &str) -> String {
    let name_c = cmd_comment_sanitize(name);
    let cfg = cmd_set_value_escape(config_dir);
    let bin = cmd_set_value_escape(claude_bin);
    format!(
        "@echo off\r\n\
         set \"CLAUDE_CONFIG_DIR={cfg}\"\r\n\
         set \"CLAUDE_BIN={bin}\"\r\n\
         if not exist \"%CLAUDE_BIN%\" set \"CLAUDE_BIN=claude\"\r\n\
         echo Signing in to Claude Code for \"{name_c}\"...\r\n\
         echo.\r\n\
         call \"%CLAUDE_BIN%\" auth login\r\n\
         echo.\r\n\
         echo Finished. You can close this window and return to Personae.\r\n\
         pause\r\n"
    )
}

// ---- cross-platform onboarding / credential-presence / size helpers --------

/// A stored login exists for this config dir (Windows/Linux signal): claude's
/// plaintext credential file is present. (macOS uses the Keychain slot instead.)
#[allow(dead_code)] // used on Windows + in tests; unreferenced in the macOS build
pub fn credentials_present_at(config_dir: &Path) -> bool {
    config_dir.join(".credentials.json").is_file()
}

/// Set hasCompletedOnboarding:true in <config_dir>/.claude.json (idempotent,
/// best-effort) so interactive `claude` skips the first-run menu. Shared by all
/// OSes; `claude auth login` stores the credential but does NOT set this flag.
pub fn mark_onboarded_at(config_dir: &Path) {
    let f = config_dir.join(".claude.json");
    let mut v: serde_json::Value = std::fs::read_to_string(&f).ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_else(|| serde_json::json!({}));
    if v.get("hasCompletedOnboarding").and_then(|b| b.as_bool()) == Some(true) { return; }
    if let Some(o) = v.as_object_mut() {
        o.insert("hasCompletedOnboarding".into(), serde_json::Value::Bool(true));
    }
    let _ = std::fs::create_dir_all(config_dir);
    if let Ok(s) = serde_json::to_string_pretty(&v) { let _ = std::fs::write(&f, s); }
}

/// Rough recursive byte count (Windows has no `du`); best-effort, ignores errors.
#[allow(dead_code)] // used on Windows (list); unreferenced in the macOS build
fn dir_size_bytes(p: &Path) -> u64 {
    let mut total = 0;
    if let Ok(rd) = std::fs::read_dir(p) {
        for e in rd.flatten() {
            let path = e.path();
            match e.metadata() {
                Ok(m) if m.is_dir() => total += dir_size_bytes(&path),
                Ok(m) => total += m.len(),
                _ => {}
            }
        }
    }
    total
}

#[allow(dead_code)] // used on Windows (list); unreferenced in the macOS build
fn human_size(bytes: u64) -> String {
    const U: [&str; 5] = ["B", "KB", "MB", "GB", "TB"];
    let (mut b, mut i) = (bytes as f64, 0);
    while b >= 1024.0 && i < U.len() - 1 { b /= 1024.0; i += 1; }
    if i == 0 { format!("{} {}", bytes, U[0]) } else { format!("{:.1} {}", b, U[i]) }
}

#[cfg(target_os = "macos")]
mod imp {
    use super::*;
    use crate::platform::{home, run};
    use std::fs;
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;

    // ~/Applications/Claude Profiles CLI/<name>.command
    pub fn launcher_root() -> PathBuf { home().join("Applications/Claude Profiles CLI") }
    // ~/Library/Application Support/ClaudeProfilesCLI/<slug>   (== CLAUDE_CONFIG_DIR)
    pub fn config_root() -> PathBuf { home().join("Library/Application Support/ClaudeProfilesCLI") }

    pub fn launcher_path(name: &str) -> PathBuf { launcher_root().join(format!("{name}.command")) }
    pub fn config_dir(slug: &str) -> PathBuf { config_root().join(slug) }

    /// Resolve the claude CLI binary (env override → PATH → common install dirs).
    pub fn claude_bin() -> Option<PathBuf> {
        if let Ok(p) = std::env::var("CLAUDE_CLI_BIN") {
            let pb = PathBuf::from(p);
            if pb.is_file() { return Some(pb); }
        }
        let (ok, out) = run("which", &["claude"]);
        if ok {
            let p = PathBuf::from(out.trim());
            if p.is_file() { return Some(p); }
        }
        for c in [
            "/opt/homebrew/bin/claude", "/usr/local/bin/claude",
            "~/.local/bin/claude", "~/.claude/local/claude", "~/.bun/bin/claude",
        ] {
            let pb = if let Some(rest) = c.strip_prefix("~/") { home().join(rest) } else { PathBuf::from(c) };
            if pb.is_file() { return Some(pb); }
        }
        None
    }

    pub fn write_launcher(name: &str, slug: &str) -> Result<(), String> {
        let cfg = config_dir(slug);
        let bin = claude_bin().map(|p| p.display().to_string()).unwrap_or_default();
        let body = render_launcher(name, &cfg.display().to_string(), &bin);
        let lp = launcher_path(name);
        fs::create_dir_all(launcher_root()).map_err(|e| e.to_string())?;
        fs::write(&lp, body).map_err(|e| e.to_string())?;
        let mut perm = fs::metadata(&lp).map_err(|e| e.to_string())?.permissions();
        perm.set_mode(0o755);
        fs::set_permissions(&lp, perm).map_err(|e| e.to_string())
    }

    /// The Keychain service claude uses for this profile's login (namespaced by
    /// config-dir hash — mirrors the CLI's own derivation). Used only to purge on
    /// delete. Default config dir would be un-suffixed, but profiles are always
    /// custom, so the hash suffix always applies.
    pub fn login_keychain_service(slug: &str) -> String {
        super::login_keychain_service_for_dir(&config_dir(slug).display().to_string())
    }

    /// Whether a login credential is stored for this profile — checked by the
    /// existence of claude's per-config-dir Keychain slot. This is the reliable
    /// signal: `claude auth status` reports a false negative once the access
    /// token expires (even though the refresh token is still valid and usage
    /// works), and `oauthAccount` in .claude.json is only populated lazily.
    pub fn login_present(slug: &str) -> bool {
        let svc = login_keychain_service(slug);
        let user = std::env::var("USER").unwrap_or_default();
        run("security", &["find-generic-password", "-s", &svc, "-a", &user]).0
    }

    /// Mark this profile's config dir as onboarded so interactive `claude` skips
    /// the first-run login/onboarding menu (`claude auth login` stores the
    /// credential but does NOT set this flag, so without it a logged-in profile
    /// still shows the menu). Idempotent + best-effort: only writes when the flag
    /// isn't already true, so it doesn't churn .claude.json on every list.
    pub fn mark_onboarded(slug: &str) {
        super::mark_onboarded_at(&config_dir(slug));
    }
}

// Windows CLI engine — WRITTEN FROM CLAUDE'S CODE + WINDOWS DOCS, NOT YET RUN
// ON REAL WINDOWS. Every process/quoting assumption is marked TODO(verify); see
// docs/WINDOWS-TEST-PLAN.md. Isolation needs ONLY CLAUDE_CONFIG_DIR: on Windows
// there is no Keychain, so claude's credential store falls back to a plaintext
// <CLAUDE_CONFIG_DIR>\.credentials.json — one config dir per account gives one
// durable, concurrently-usable login. No keychain hashing, no token injection.
#[cfg(windows)]
mod imp_win {
    use super::*;
    use std::fs;
    use std::path::PathBuf;

    fn appdata() -> PathBuf { PathBuf::from(std::env::var("APPDATA").unwrap_or_default()) }
    fn localappdata() -> PathBuf { PathBuf::from(std::env::var("LOCALAPPDATA").unwrap_or_default()) }
    fn userprofile() -> PathBuf { PathBuf::from(std::env::var("USERPROFILE").unwrap_or_default()) }

    // %LOCALAPPDATA%\ClaudeProfilesCLI\apps\<slug>.cmd  (+ .name sidecar, + _login\<slug>.cmd)
    pub fn launcher_root() -> PathBuf { localappdata().join("ClaudeProfilesCLI").join("apps") }
    // %APPDATA%\ClaudeProfilesCLI\<slug>   == CLAUDE_CONFIG_DIR
    pub fn config_root() -> PathBuf { appdata().join("ClaudeProfilesCLI") }

    pub fn launcher_path(slug: &str) -> PathBuf { launcher_root().join(format!("{slug}.cmd")) }
    pub fn name_path(slug: &str) -> PathBuf { launcher_root().join(format!("{slug}.name")) }
    pub fn login_path(slug: &str) -> PathBuf { launcher_root().join("_login").join(format!("{slug}.cmd")) }
    pub fn config_dir(slug: &str) -> PathBuf { config_root().join(slug) }

    /// Resolve the claude CLI: env override → `where claude` → common installs.
    pub fn claude_bin() -> Option<PathBuf> {
        if let Ok(p) = std::env::var("CLAUDE_CLI_BIN") {
            let pb = PathBuf::from(p);
            if pb.is_file() { return Some(pb); }
        }
        // TODO(verify): `where claude` resolves the shim on PATH (npm/bun/etc.).
        let (ok, out) = crate::platform::run("where", &["claude"]);
        if ok {
            for line in out.lines() {
                let pb = PathBuf::from(line.trim());
                if pb.is_file() { return Some(pb); }
            }
        }
        // TODO(verify): these are the common per-user install layouts on Windows.
        let candidates = [
            appdata().join(r"npm\claude.cmd"),
            appdata().join(r"npm\claude.exe"),
            localappdata().join(r"npm\claude.cmd"),
            userprofile().join(r".bun\bin\claude.exe"),
            userprofile().join(r".local\bin\claude.exe"),
            userprofile().join(r".claude\local\claude.exe"),
        ];
        if let Some(p) = candidates.into_iter().find(|p| p.is_file()) {
            return Some(p);
        }
        // Last resort (Windows field report): the shim may be present but its own
        // wrapper broken, or `where claude` may have missed because the GUI has no
        // npm bin on PATH. Probe the native exe the package unpacks, using both a
        // fixed npm root and every dir `where claude` did surface.
        let mut npm_dirs: Vec<PathBuf> = vec![appdata().join("npm")];
        let (ok, out) = crate::platform::run("where", &["claude"]);
        if ok {
            for line in out.lines() {
                if let Some(dir) = PathBuf::from(line.trim()).parent() {
                    npm_dirs.push(dir.to_path_buf());
                }
            }
        }
        for dir in npm_dirs {
            let exe = super::nested_win_claude_exe(&dir);
            if exe.is_file() {
                return Some(exe);
            }
        }
        None
    }

    pub fn claude_bin_string() -> String {
        claude_bin().map(|p| p.display().to_string()).unwrap_or_else(|| "claude".into())
    }

    pub fn write_launcher(name: &str, slug: &str) -> Result<(), String> {
        fs::create_dir_all(launcher_root()).map_err(|e| e.to_string())?;
        let cfg = config_dir(slug).display().to_string();
        let body = render_launcher_win(name, &cfg, &claude_bin_string());
        fs::write(launcher_path(slug), body).map_err(|e| e.to_string())?;
        fs::write(name_path(slug), name).map_err(|e| e.to_string())?; // display-name sidecar
        Ok(())
    }

    pub fn write_login_script(name: &str, slug: &str) -> Result<PathBuf, String> {
        let dir = launcher_root().join("_login");
        fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let cfg = config_dir(slug).display().to_string();
        let body = render_login_win(name, &cfg, &claude_bin_string());
        let p = login_path(slug);
        fs::write(&p, body).map_err(|e| e.to_string())?;
        Ok(p)
    }

    pub fn login_present(slug: &str) -> bool { credentials_present_at(&config_dir(slug)) }
    pub fn mark_onboarded(slug: &str) { mark_onboarded_at(&config_dir(slug)); }
}

/// Absolute path to claude if resolvable, else the bare command name "claude".
/// Used by ide.rs so a folderOpen task's `command` works regardless of the
/// login shell's PATH. Lives at the module root (not inside `mod imp`, which is
/// macOS-only) so it compiles on every target.
#[cfg(target_os = "macos")]
pub fn imp_claude_bin_string() -> String {
    imp::claude_bin().map(|p| p.display().to_string()).unwrap_or_else(|| "claude".to_string())
}
#[cfg(windows)]
pub fn imp_claude_bin_string() -> String { imp_win::claude_bin_string() }
#[cfg(not(any(target_os = "macos", windows)))]
pub fn imp_claude_bin_string() -> String { "claude".to_string() }

/// If this profile has a stored login, ensure its config dir is marked onboarded
/// so interactive `claude` (via Launch or an IDE terminal) skips the first-run
/// login menu and goes straight in on the stored account. No-op when not logged
/// in (we WANT the menu then, so the user can sign in). Called by cli::launch,
/// cli::list, and ide::open_in_ide.
#[cfg(target_os = "macos")]
pub fn ensure_onboarded(name: &str) {
    let slug = crate::platform::slugify(name);
    if imp::login_present(&slug) { imp::mark_onboarded(&slug); }
}
#[cfg(windows)]
pub fn ensure_onboarded(name: &str) {
    let slug = crate::platform::slugify(name);
    if imp_win::login_present(&slug) { imp_win::mark_onboarded(&slug); }
}
#[cfg(not(any(target_os = "macos", windows)))]
pub fn ensure_onboarded(_name: &str) {}

// ---- public API (macOS) --------------------------------------------------
#[cfg(target_os = "macos")]
pub fn available() -> bool { imp::claude_bin().is_some() }

#[cfg(target_os = "macos")]
pub fn create(name: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    if slug.is_empty() { return Err("Name must contain letters or numbers.".into()); }
    let lp = imp::launcher_path(name);
    if lp.exists() { return Err(format!("CLI profile already exists: {}", lp.display())); }
    std::fs::create_dir_all(imp::config_dir(&slug)).map_err(|e| e.to_string())?;
    imp::write_launcher(name, &slug)?;
    Ok(())
}

/// Open a Terminal in this profile's config dir running `claude auth login` — the
/// one-time real sign-in. The credential is stored in this profile's own
/// Keychain slot (namespaced by config dir), isolated from other profiles.
#[cfg(target_os = "macos")]
pub fn login(name: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    if !imp::launcher_path(name).exists() { return Err(format!("No such CLI profile: {name}")); }
    let bin = imp::claude_bin().ok_or("Claude Code CLI not found (install `claude`).")?;
    let cfg = imp::config_dir(&slug);
    let shell_cmd = format!(
        "export CLAUDE_CONFIG_DIR={}; {} auth login",
        sh_quote(&cfg.display().to_string()), sh_quote(&bin.display().to_string())
    );
    let as_arg = shell_cmd.replace('\\', "\\\\").replace('"', "\\\"");
    let script = format!("tell application \"Terminal\" to do script \"{}\"", as_arg);
    let (ok, out) = crate::platform::run("osascript", &["-e", &script, "-e", "tell application \"Terminal\" to activate"]);
    if ok { Ok(()) } else { Err(out.trim().to_string()) }
}

#[cfg(target_os = "macos")]
pub fn launch(name: &str) -> Result<(), String> {
    let lp = imp::launcher_path(name);
    if !lp.exists() { return Err(format!("No such CLI profile: {name}")); }
    ensure_onboarded(name); // skip the first-run menu if already logged in
    let (ok, e) = crate::platform::run("open", &[&lp.display().to_string()]);
    if ok { Ok(()) } else { Err(e) }
}

#[cfg(target_os = "macos")]
pub fn list() -> Vec<CliProfile> {
    use crate::platform::{run, slugify, to_secs};
    let mut out = vec![];
    let rd = match std::fs::read_dir(imp::launcher_root()) { Ok(r) => r, Err(_) => return out };
    for e in rd.flatten() {
        let p = e.path();
        if p.extension().map_or(false, |x| x == "command") {
            let name = p.file_stem().unwrap_or_default().to_string_lossy().to_string();
            let slug = slugify(&name);
            let cfg = imp::config_dir(&slug);
            let data_size = if cfg.exists() {
                let (_, o) = run("du", &["-sh", &cfg.display().to_string()]);
                o.split('\t').next().unwrap_or("—").trim().to_string()
            } else { "—".into() };
            let account_email = std::fs::read_to_string(cfg.join(".claude.json")).ok()
                .and_then(|j| extract_email(&j));
            // Reliable signal = the login's Keychain slot exists (email is only a
            // lazily-cached display value that may lag behind the actual login).
            let logged_in = imp::login_present(&slug);
            if logged_in { imp::mark_onboarded(&slug); } // self-heal: skip first-run menu once logged in
            let md = std::fs::metadata(&cfg).ok();
            let created = md.as_ref().and_then(|m| m.created().ok()).and_then(to_secs);
            let last_active = md.as_ref().and_then(|m| m.modified().ok()).and_then(to_secs);
            out.push(CliProfile {
                name, slug,
                config_dir: cfg.display().to_string(),
                launcher_path: p.display().to_string(),
                logged_in, account_email, data_size, created, last_active,
            });
        }
    }
    out.sort_by(|a, b| a.name.to_lowercase().cmp(&b.name.to_lowercase()));
    out
}

#[cfg(target_os = "macos")]
pub fn delete(name: &str, purge: bool) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    let lp = imp::launcher_path(name);
    if !lp.exists() { return Err(format!("No such CLI profile: {name}")); }
    std::fs::remove_file(&lp).map_err(|e| e.to_string())?;
    if purge {
        // remove claude's per-profile login from the Keychain, then the data dir
        let svc = imp::login_keychain_service(&slug);
        let user = std::env::var("USER").unwrap_or_default();
        let _ = crate::platform::run("security", &["delete-generic-password", "-s", &svc, "-a", &user]);
        let cfg = imp::config_dir(&slug);
        if cfg.exists() { std::fs::remove_dir_all(&cfg).map_err(|e| e.to_string())?; }
    }
    Ok(())
}

// ---- public API (Windows) ------------------------------------------------
// Isolation is by CLAUDE_CONFIG_DIR alone (see imp_win header). Every process /
// quoting assumption below is marked TODO(verify) for the real-Windows pass.
#[cfg(windows)]
pub fn available() -> bool { imp_win::claude_bin().is_some() }

#[cfg(windows)]
pub fn create(name: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    if slug.is_empty() { return Err("Name must contain letters or numbers.".into()); }
    if imp_win::launcher_path(&slug).exists() { return Err(format!("CLI account already exists: {name}")); }
    std::fs::create_dir_all(imp_win::config_dir(&slug)).map_err(|e| e.to_string())?;
    imp_win::write_launcher(name, &slug)?;
    Ok(())
}

/// Open a one-shot console running `claude auth login` for this account's
/// CLAUDE_CONFIG_DIR — the real sign-in. On Windows the credential is written to
/// <config_dir>\.credentials.json (Keychain is absent), isolated per account.
#[cfg(windows)]
pub fn login(name: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    if !imp_win::launcher_path(&slug).exists() { return Err(format!("No such CLI account: {name}")); }
    imp_win::claude_bin().ok_or("Claude Code CLI not found (install `claude`).")?;
    let script = imp_win::write_login_script(name, &slug)?;
    // Open the one-shot login console in its own window. TODO(verify) start quoting:
    // the empty "" is the (unused) window title so a quoted script path is not
    // mistaken for the title.
    let (ok, out) = crate::platform::run("cmd", &["/C", "start", "", &script.display().to_string()]);
    if ok { Ok(()) } else { Err(out.trim().to_string()) }
}

#[cfg(windows)]
pub fn launch(name: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    let lp = imp_win::launcher_path(&slug);
    if !lp.exists() { return Err(format!("No such CLI account: {name}")); }
    ensure_onboarded(name); // skip the first-run menu if already logged in
    // New interactive console running the launcher (keeps window; user gets a
    // claude REPL). `cmd /K` keeps the window open. Pass the launcher path BARE
    // (no manual quotes): std::process::Command already quotes each arg, so a
    // pre-quoted string would reach cmd as literal quotes. TODO(verify) start/K.
    let (ok, out) = crate::platform::run(
        "cmd",
        &["/C", "start", "", "cmd", "/K", &lp.display().to_string()],
    );
    if ok { Ok(()) } else { Err(out.trim().to_string()) }
}

#[cfg(windows)]
pub fn list() -> Vec<CliProfile> {
    use crate::platform::to_secs;
    let mut out = vec![];
    let rd = match std::fs::read_dir(imp_win::launcher_root()) { Ok(r) => r, Err(_) => return out };
    for e in rd.flatten() {
        let p = e.path();
        if p.extension().map_or(false, |x| x == "cmd") {
            let slug = p.file_stem().unwrap_or_default().to_string_lossy().to_string();
            let name = std::fs::read_to_string(imp_win::name_path(&slug)).ok()
                .map(|s| s.trim().to_string()).filter(|s| !s.is_empty())
                .unwrap_or_else(|| slug.clone());
            let cfg = imp_win::config_dir(&slug);
            let data_size = if cfg.exists() { human_size(dir_size_bytes(&cfg)) } else { "—".into() };
            let account_email = std::fs::read_to_string(cfg.join(".claude.json")).ok()
                .and_then(|j| extract_email(&j));
            let logged_in = imp_win::login_present(&slug);
            if logged_in { imp_win::mark_onboarded(&slug); } // self-heal: skip first-run menu
            let md = std::fs::metadata(&cfg).ok();
            let created = md.as_ref().and_then(|m| m.created().ok()).and_then(to_secs);
            let last_active = md.as_ref().and_then(|m| m.modified().ok()).and_then(to_secs);
            out.push(CliProfile {
                name, slug,
                config_dir: cfg.display().to_string(),
                launcher_path: p.display().to_string(),
                logged_in, account_email, data_size, created, last_active,
            });
        }
    }
    out.sort_by(|a, b| a.name.to_lowercase().cmp(&b.name.to_lowercase()));
    out
}

#[cfg(windows)]
pub fn delete(name: &str, purge: bool) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    let lp = imp_win::launcher_path(&slug);
    if !lp.exists() { return Err(format!("No such CLI account: {name}")); }
    std::fs::remove_file(&lp).map_err(|e| e.to_string())?;
    let _ = std::fs::remove_file(imp_win::name_path(&slug));
    let _ = std::fs::remove_file(imp_win::login_path(&slug));
    if purge {
        // No Keychain on Windows: the login lives in <config_dir>\.credentials.json,
        // which is removed with the dir.
        let cfg = imp_win::config_dir(&slug);
        if cfg.exists() { std::fs::remove_dir_all(&cfg).map_err(|e| e.to_string())?; }
    }
    Ok(())
}

// ---- public API (Linux/other stubs; not yet implemented) -----------------
#[cfg(not(any(target_os = "macos", windows)))]
const NOT_YET: &str = "CLI accounts are macOS/Windows-only for now.";
#[cfg(not(any(target_os = "macos", windows)))]
pub fn available() -> bool { false }
#[cfg(not(any(target_os = "macos", windows)))]
pub fn list() -> Vec<CliProfile> { vec![] }
#[cfg(not(any(target_os = "macos", windows)))]
pub fn create(_name: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(any(target_os = "macos", windows)))]
pub fn login(_name: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(any(target_os = "macos", windows)))]
pub fn launch(_name: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(any(target_os = "macos", windows)))]
pub fn delete(_name: &str, _purge: bool) -> Result<(), String> { Err(NOT_YET.into()) }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launcher_sets_config_dir_and_execs() {
        let s = render_launcher("Work", "/tmp/cfg dir", "/opt/homebrew/bin/claude");
        assert!(s.contains("export CLAUDE_CONFIG_DIR=\"/tmp/cfg dir\""));
        assert!(s.trim_end().ends_with("exec \"$CLAUDE_BIN\" \"$@\""));
        assert!(!s.contains("security"));                // no keychain reads
        assert!(!s.contains("CLAUDE_CODE_OAUTH_TOKEN"));  // no token injection
    }

    #[test]
    fn sh_dq_escape_neutralizes_metachars() {
        assert_eq!(sh_dq_escape("a\"$`\\b"), "a\\\"\\$\\`\\\\b");
    }

    #[test]
    fn launcher_escapes_quotes_in_name() {
        let s = render_launcher("Ac\"me", "/tmp/x", "/bin/claude");
        assert!(s.contains("Ac\\\"me"));
    }

    #[test]
    fn sh_quote_escapes_single_quotes() {
        assert_eq!(sh_quote("/tmp/plain"), "'/tmp/plain'");
        assert_eq!(sh_quote("/Users/O'Brien/x"), "'/Users/O'\\''Brien/x'");
    }

    #[test]
    fn keychain_service_matches_claude_derivation() {
        // Verified empirically: real /login in this dir created Keychain item
        // "Claude Code-credentials-5f560a22".
        assert_eq!(
            login_keychain_service_for_dir("/Users/amoryzenith/Library/Application Support/ClaudeProfilesCLI/proto1"),
            "Claude Code-credentials-5f560a22"
        );
    }

    #[test]
    fn extract_email_works() {
        let j = r#"{"userID":"x","oauthAccount":{"emailAddress":"a@b.com","org":"y"}}"#;
        assert_eq!(extract_email(j).as_deref(), Some("a@b.com"));
        assert_eq!(extract_email(r#"{"no":"email"}"#), None);
    }

    // ---- Windows pure-helper tests (run on macOS) ------------------------

    #[test]
    fn win_launcher_sets_config_dir_and_calls_bin() {
        let s = render_launcher_win("Work", r"C:\Users\me\AppData\Roaming\ClaudeProfilesCLI\work", r"C:\Users\me\AppData\Roaming\npm\claude.cmd");
        assert!(s.starts_with("@echo off\r\n"));
        assert!(s.contains("set \"CLAUDE_CONFIG_DIR=C:\\Users\\me\\AppData\\Roaming\\ClaudeProfilesCLI\\work\""));
        assert!(s.contains("set \"CLAUDE_BIN=C:\\Users\\me\\AppData\\Roaming\\npm\\claude.cmd\""));
        assert!(s.contains("if not exist \"%CLAUDE_BIN%\" set \"CLAUDE_BIN=claude\""));
        assert!(s.contains("call \"%CLAUDE_BIN%\" %*"));
        assert!(s.ends_with("\r\n"));
    }

    #[test]
    fn win_value_escape_doubles_percent() {
        assert_eq!(cmd_set_value_escape("a%b%c"), "a%%b%%c");
        assert_eq!(cmd_set_value_escape(r"C:\plain\path"), r"C:\plain\path");
    }

    #[test]
    fn win_login_script_runs_auth_login_and_pauses() {
        let s = render_login_win("Work", r"C:\cfg\work", r"C:\bin\claude.cmd");
        assert!(s.contains("set \"CLAUDE_CONFIG_DIR=C:\\cfg\\work\""));
        assert!(s.contains("set \"CLAUDE_BIN=C:\\bin\\claude.cmd\""));
        assert!(s.contains("call \"%CLAUDE_BIN%\" auth login"));
        assert!(s.contains("pause"));
    }

    #[test]
    fn credentials_present_detects_file() {
        let d = std::env::temp_dir().join(format!("cli-cred-{}", std::process::id()));
        std::fs::create_dir_all(&d).unwrap();
        assert!(!credentials_present_at(&d));
        std::fs::write(d.join(".credentials.json"), r#"{"claudeAiOauth":{}}"#).unwrap();
        assert!(credentials_present_at(&d));
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn mark_onboarded_sets_flag_idempotently() {
        let d = std::env::temp_dir().join(format!("cli-onb-{}", std::process::id()));
        std::fs::create_dir_all(&d).unwrap();
        mark_onboarded_at(&d);
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(d.join(".claude.json")).unwrap()).unwrap();
        assert_eq!(v["hasCompletedOnboarding"], serde_json::json!(true));
        // Second call is a no-op (flag already true) and must not error.
        mark_onboarded_at(&d);
        let v2: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(d.join(".claude.json")).unwrap()).unwrap();
        assert_eq!(v2["hasCompletedOnboarding"], serde_json::json!(true));
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn win_launcher_comment_is_single_line_and_escapes_percent() {
        // The display name lands ONLY in the REM comment. CR/LF must be stripped
        // so an injected `set EVIL=1` cannot break out into its own command line,
        // and `%` must be doubled so it isn't expanded.
        let s = render_launcher_win("a\r\nset EVIL=1\r\nrem %x%", r"C:\cfg\a", r"C:\bin\claude.cmd");
        let rem_lines: Vec<&str> = s.lines().filter(|l| l.trim_start().starts_with("REM")).collect();
        assert_eq!(rem_lines.len(), 1, "name must not inject extra lines");
        let rem = rem_lines[0];
        assert!(rem.contains("aset EVIL=1rem"), "CR/LF should be stripped, got: {rem}");
        assert!(rem.contains("%%x%%"), "percent must be doubled in the comment");
        // The injected fragment must never appear as its own command line.
        assert!(!s.lines().any(|l| l.trim() == "set EVIL=1"));
    }

    #[test]
    fn mark_onboarded_preserves_existing_json() {
        let d = std::env::temp_dir().join(format!("cli-onb-preserve-{}", std::process::id()));
        std::fs::create_dir_all(&d).unwrap();
        std::fs::write(
            d.join(".claude.json"),
            r#"{"oauthAccount":{"emailAddress":"a@b.com"},"foo":"bar"}"#,
        ).unwrap();
        mark_onboarded_at(&d);
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(d.join(".claude.json")).unwrap()).unwrap();
        assert_eq!(v["hasCompletedOnboarding"], serde_json::json!(true));
        assert_eq!(v["foo"], serde_json::json!("bar"));
        assert_eq!(v["oauthAccount"]["emailAddress"], serde_json::json!("a@b.com"));
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn nested_win_exe_path_is_assembled() {
        // Given the npm global bin dir (where the `claude` shim lives), we derive
        // the native exe the claude-code package unpacks for win32-x64.
        let base = std::path::Path::new("NPMROOT");
        let got = nested_win_claude_exe(base);
        let s = got.to_string_lossy();
        assert!(got.ends_with("claude.exe"), "must end at claude.exe: {s}");
        assert!(s.contains("@anthropic-ai"), "must nest under @anthropic-ai: {s}");
        assert!(s.contains("claude-code-win32-x64"), "must hit the win32-x64 pkg: {s}");
        // The nesting is claude-code -> node_modules -> claude-code-win32-x64, so
        // exactly two `node_modules` segments appear.
        assert_eq!(s.matches("node_modules").count(), 2, "exactly two node_modules: {s}");
    }
}
