// Claude Code CLI profile engine. Parallels macos.rs (Desktop), but isolates the
// *CLI*: each profile is a real Claude login, seeded by a one-time `/login`
// inside its own CLAUDE_CONFIG_DIR. Claude Code itself namespaces the OAuth
// credential in the macOS Keychain by a hash of CLAUDE_CONFIG_DIR (service
// `Claude Code-credentials-<sha256(config_dir)[:8]>`), so distinct config dirs
// give distinct, durable, concurrently-usable logins — with zero app-managed
// secrets. No token injection, no shim, no setup-token capture.
use serde::Serialize;

#[derive(Serialize, Clone)]
pub struct CliProfile {
    pub name: String,
    pub slug: String,
    pub config_dir: String,    // CLAUDE_CONFIG_DIR for this profile
    pub launcher_path: String, // the generated .command
    pub logged_in: bool,       // an oauthAccount exists in <config_dir>/.claude.json
    pub account_email: Option<String>, // parsed from <config_dir>/.claude.json if present
    pub data_size: String,
    pub created: Option<u64>,
    pub last_active: Option<u64>,
}

/// Escape a string for safe interpolation inside a double-quoted bash string.
pub fn sh_dq_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(c, '"' | '\\' | '$' | '`') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// Wrap a string as a safe POSIX single-quoted shell word (handles embedded ').
pub fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// The bash body of a profile launcher. Sets the profile's CLAUDE_CONFIG_DIR and
/// execs the real claude CLI — claude resolves the per-profile login from its
/// own Keychain slot (namespaced by config dir). On first run claude shows the
/// login prompt; that one-time /login seeds the profile.
pub fn render_launcher(name: &str, config_dir: &str, claude_bin: &str) -> String {
    let name_e = sh_dq_escape(name);
    let cfg_e = sh_dq_escape(config_dir);
    let bin_e = sh_dq_escape(claude_bin);
    format!(
        "#!/bin/bash\n\
         # Generated by Claude Profiles — CLI account launcher for \"{name_e}\".\n\
         export CLAUDE_CONFIG_DIR=\"{cfg_e}\"\n\
         CLAUDE_BIN=\"{bin_e}\"\n\
         [ -x \"$CLAUDE_BIN\" ] || CLAUDE_BIN=\"$(command -v claude)\"\n\
         exec \"$CLAUDE_BIN\" \"$@\"\n"
    )
}

/// The Keychain service name claude uses for a login stored under `config_dir`
/// (namespaced by config-dir hash). Pure + testable — verified against a real
/// profile this session (see test).
pub fn login_keychain_service_for_dir(config_dir: &str) -> String {
    use sha2::{Digest, Sha256};
    let h = Sha256::digest(config_dir.as_bytes());
    let hex: String = h.iter().take(4).map(|b| format!("{b:02x}")).collect(); // first 8 hex chars
    format!("Claude Code-credentials-{hex}")
}

/// Cheap extract of oauthAccount.emailAddress from a .claude.json body without
/// pulling in serde_json.
pub fn extract_email(json: &str) -> Option<String> {
    let key = "\"emailAddress\"";
    let i = json.find(key)? + key.len();
    let rest = &json[i..];
    let start = rest.find('"')? + 1;
    let after = &rest[start..];
    let end = after.find('"')?;
    let email = &after[..end];
    if email.contains('@') { Some(email.to_string()) } else { None }
}

#[cfg(target_os = "macos")]
mod imp {
    use super::*;
    use crate::platform::{home, run};
    use std::fs;
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;

    // ~/Applications/Claude Profiles CLI/<name>.command
    pub fn launcher_root() -> PathBuf { home().join("Applications/Claude Profiles CLI") }
    // ~/Library/Application Support/ClaudeProfilesCLI/<slug>   (== CLAUDE_CONFIG_DIR)
    pub fn config_root() -> PathBuf { home().join("Library/Application Support/ClaudeProfilesCLI") }

    pub fn launcher_path(name: &str) -> PathBuf { launcher_root().join(format!("{name}.command")) }
    pub fn config_dir(slug: &str) -> PathBuf { config_root().join(slug) }

    /// Resolve the claude CLI binary (env override → PATH → common install dirs).
    pub fn claude_bin() -> Option<PathBuf> {
        if let Ok(p) = std::env::var("CLAUDE_CLI_BIN") {
            let pb = PathBuf::from(p);
            if pb.is_file() { return Some(pb); }
        }
        let (ok, out) = run("which", &["claude"]);
        if ok {
            let p = PathBuf::from(out.trim());
            if p.is_file() { return Some(p); }
        }
        for c in [
            "/opt/homebrew/bin/claude", "/usr/local/bin/claude",
            "~/.local/bin/claude", "~/.claude/local/claude", "~/.bun/bin/claude",
        ] {
            let pb = if let Some(rest) = c.strip_prefix("~/") { home().join(rest) } else { PathBuf::from(c) };
            if pb.is_file() { return Some(pb); }
        }
        None
    }

    pub fn write_launcher(name: &str, slug: &str) -> Result<(), String> {
        let cfg = config_dir(slug);
        let bin = claude_bin().map(|p| p.display().to_string()).unwrap_or_default();
        let body = render_launcher(name, &cfg.display().to_string(), &bin);
        let lp = launcher_path(name);
        fs::create_dir_all(launcher_root()).map_err(|e| e.to_string())?;
        fs::write(&lp, body).map_err(|e| e.to_string())?;
        let mut perm = fs::metadata(&lp).map_err(|e| e.to_string())?.permissions();
        perm.set_mode(0o755);
        fs::set_permissions(&lp, perm).map_err(|e| e.to_string())
    }

    /// The Keychain service claude uses for this profile's login (namespaced by
    /// config-dir hash — mirrors the CLI's own derivation). Used only to purge on
    /// delete. Default config dir would be un-suffixed, but profiles are always
    /// custom, so the hash suffix always applies.
    pub fn login_keychain_service(slug: &str) -> String {
        super::login_keychain_service_for_dir(&config_dir(slug).display().to_string())
    }
}

/// Absolute path to claude if resolvable, else the bare command name "claude".
/// Used by ide.rs so a folderOpen task's `command` works regardless of the
/// login shell's PATH. Lives at the module root (not inside `mod imp`, which is
/// macOS-only) so it compiles on every target.
#[cfg(target_os = "macos")]
pub fn imp_claude_bin_string() -> String {
    imp::claude_bin().map(|p| p.display().to_string()).unwrap_or_else(|| "claude".to_string())
}
#[cfg(not(target_os = "macos"))]
pub fn imp_claude_bin_string() -> String { "claude".to_string() }

// ---- public API (macOS) --------------------------------------------------
#[cfg(target_os = "macos")]
pub fn available() -> bool { imp::claude_bin().is_some() }

#[cfg(target_os = "macos")]
pub fn create(name: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    if slug.is_empty() { return Err("Name must contain letters or numbers.".into()); }
    let lp = imp::launcher_path(name);
    if lp.exists() { return Err(format!("CLI profile already exists: {}", lp.display())); }
    std::fs::create_dir_all(imp::config_dir(&slug)).map_err(|e| e.to_string())?;
    imp::write_launcher(name, &slug)?;
    Ok(())
}

/// Open a Terminal in this profile's config dir so the user can run the one-time
/// `/login`. First run shows the login menu; after logging in, the credential
/// lives in the profile's own Keychain slot.
#[cfg(target_os = "macos")]
pub fn login(name: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    if !imp::launcher_path(name).exists() { return Err(format!("No such CLI profile: {name}")); }
    let bin = imp::claude_bin().ok_or("Claude Code CLI not found (install `claude`).")?;
    let cfg = imp::config_dir(&slug);
    let shell_cmd = format!(
        "export CLAUDE_CONFIG_DIR={}; {} /login",
        sh_quote(&cfg.display().to_string()), sh_quote(&bin.display().to_string())
    );
    let as_arg = shell_cmd.replace('\\', "\\\\").replace('"', "\\\"");
    let script = format!("tell application \"Terminal\" to do script \"{}\"", as_arg);
    let (ok, out) = crate::platform::run("osascript", &["-e", &script, "-e", "tell application \"Terminal\" to activate"]);
    if ok { Ok(()) } else { Err(out.trim().to_string()) }
}

#[cfg(target_os = "macos")]
pub fn launch(name: &str) -> Result<(), String> {
    let lp = imp::launcher_path(name);
    if !lp.exists() { return Err(format!("No such CLI profile: {name}")); }
    let (ok, e) = crate::platform::run("open", &[&lp.display().to_string()]);
    if ok { Ok(()) } else { Err(e) }
}

#[cfg(target_os = "macos")]
pub fn list() -> Vec<CliProfile> {
    use crate::platform::{run, slugify, to_secs};
    let mut out = vec![];
    let rd = match std::fs::read_dir(imp::launcher_root()) { Ok(r) => r, Err(_) => return out };
    for e in rd.flatten() {
        let p = e.path();
        if p.extension().map_or(false, |x| x == "command") {
            let name = p.file_stem().unwrap_or_default().to_string_lossy().to_string();
            let slug = slugify(&name);
            let cfg = imp::config_dir(&slug);
            let data_size = if cfg.exists() {
                let (_, o) = run("du", &["-sh", &cfg.display().to_string()]);
                o.split('\t').next().unwrap_or("—").trim().to_string()
            } else { "—".into() };
            let account_email = std::fs::read_to_string(cfg.join(".claude.json")).ok()
                .and_then(|j| extract_email(&j));
            let logged_in = account_email.is_some();
            let md = std::fs::metadata(&cfg).ok();
            let created = md.as_ref().and_then(|m| m.created().ok()).and_then(to_secs);
            let last_active = md.as_ref().and_then(|m| m.modified().ok()).and_then(to_secs);
            out.push(CliProfile {
                name, slug,
                config_dir: cfg.display().to_string(),
                launcher_path: p.display().to_string(),
                logged_in, account_email, data_size, created, last_active,
            });
        }
    }
    out.sort_by(|a, b| a.name.to_lowercase().cmp(&b.name.to_lowercase()));
    out
}

#[cfg(target_os = "macos")]
pub fn delete(name: &str, purge: bool) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(name);
    let lp = imp::launcher_path(name);
    if !lp.exists() { return Err(format!("No such CLI profile: {name}")); }
    std::fs::remove_file(&lp).map_err(|e| e.to_string())?;
    if purge {
        // remove claude's per-profile login from the Keychain, then the data dir
        let svc = imp::login_keychain_service(&slug);
        let user = std::env::var("USER").unwrap_or_default();
        let _ = crate::platform::run("security", &["delete-generic-password", "-s", &svc, "-a", &user]);
        let cfg = imp::config_dir(&slug);
        if cfg.exists() { std::fs::remove_dir_all(&cfg).map_err(|e| e.to_string())?; }
    }
    Ok(())
}

// ---- public API (non-macOS stubs; Phase 3 will implement Win/Linux) ------
#[cfg(not(target_os = "macos"))]
const NOT_YET: &str = "CLI profiles are macOS-only for now.";
#[cfg(not(target_os = "macos"))]
pub fn available() -> bool { false }
#[cfg(not(target_os = "macos"))]
pub fn list() -> Vec<CliProfile> { vec![] }
#[cfg(not(target_os = "macos"))]
pub fn create(_name: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(target_os = "macos"))]
pub fn login(_name: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(target_os = "macos"))]
pub fn launch(_name: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(target_os = "macos"))]
pub fn delete(_name: &str, _purge: bool) -> Result<(), String> { Err(NOT_YET.into()) }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launcher_sets_config_dir_and_execs() {
        let s = render_launcher("Work", "/tmp/cfg dir", "/opt/homebrew/bin/claude");
        assert!(s.contains("export CLAUDE_CONFIG_DIR=\"/tmp/cfg dir\""));
        assert!(s.trim_end().ends_with("exec \"$CLAUDE_BIN\" \"$@\""));
        assert!(!s.contains("security"));                // no keychain reads
        assert!(!s.contains("CLAUDE_CODE_OAUTH_TOKEN"));  // no token injection
    }

    #[test]
    fn sh_dq_escape_neutralizes_metachars() {
        assert_eq!(sh_dq_escape("a\"$`\\b"), "a\\\"\\$\\`\\\\b");
    }

    #[test]
    fn launcher_escapes_quotes_in_name() {
        let s = render_launcher("Ac\"me", "/tmp/x", "/bin/claude");
        assert!(s.contains("Ac\\\"me"));
    }

    #[test]
    fn sh_quote_escapes_single_quotes() {
        assert_eq!(sh_quote("/tmp/plain"), "'/tmp/plain'");
        assert_eq!(sh_quote("/Users/O'Brien/x"), "'/Users/O'\\''Brien/x'");
    }

    #[test]
    fn keychain_service_matches_claude_derivation() {
        // Verified empirically: real /login in this dir created Keychain item
        // "Claude Code-credentials-5f560a22".
        assert_eq!(
            login_keychain_service_for_dir("/Users/amoryzenith/Library/Application Support/ClaudeProfilesCLI/proto1"),
            "Claude Code-credentials-5f560a22"
        );
    }

    #[test]
    fn extract_email_works() {
        let j = r#"{"userID":"x","oauthAccount":{"emailAddress":"a@b.com","org":"y"}}"#;
        assert_eq!(extract_email(j).as_deref(), Some("a@b.com"));
        assert_eq!(extract_email(r#"{"no":"email"}"#), None);
    }
}
