// IDE integration: launch a CLI account inside a VS Code-family IDE at a project.
// A Claude Code account is chosen by the process env (CLAUDE_CONFIG_DIR + token).
// We make that env present in an IDE's integrated terminal without ever writing
// the secret into the project: seamless mode prepends a per-profile `bin/` dir
// (holding a `claude` shim that reads the Keychain) to the workspace terminal PATH.
use serde::{Deserialize, Serialize};

#[derive(Serialize, Clone)]
pub struct Ide {
    pub id: String,       // "vscode" | "cursor" | "windsurf" | "antigravity"
    pub name: String,     // display name
    pub cli_path: String, // resolved folder-opening CLI
}

#[derive(Serialize, Deserialize, Clone)]
pub struct Workspace {
    pub id: String,           // "<ide_id><account_slug><project_path>" — stable, unique per binding
    pub account_slug: String,
    pub account_name: String,
    pub ide_id: String,
    pub ide_name: String,
    pub project_path: String,
    pub mode: String,         // "seamless" | "wrapper"
    pub created: Option<u64>,
    pub last_opened: Option<u64>,
}

/// Deterministic id for a binding (dedupes re-adds of the same triple).
pub fn workspace_id(ide_id: &str, account_slug: &str, project_path: &str) -> String {
    format!("{ide_id}\u{1}{account_slug}\u{1}{project_path}")
}

/// The `claude` **shim** body for a profile's private bin dir. Named `claude`, it
/// must exec the REAL claude by ABSOLUTE path (never `command -v claude`, which
/// would find the shim itself and recurse). Reads the per-slug Keychain
/// credential and branches by prefix. `real_claude` is the absolute path to the
/// actual claude binary.
pub fn render_shim(slug: &str, config_dir: &str, real_claude: &str) -> String {
    // config_dir/real_claude are app-controlled paths; slug is [a-z0-9-].
    format!(
        "#!/bin/bash\n\
         # Generated by Claude Profiles — `claude` shim for CLI account \"{slug}\".\n\
         export CLAUDE_CONFIG_DIR=\"{config_dir}\"\n\
         CRED=\"$(security find-generic-password -w -s \"com.claudeprofiles.cli.{slug}\" -a \"{slug}\" 2>/dev/null)\"\n\
         if [ -n \"$CRED\" ]; then\n\
         \x20 case \"$CRED\" in\n\
         \x20   sk-ant-api*) export ANTHROPIC_API_KEY=\"$CRED\" ;;\n\
         \x20   *)           export CLAUDE_CODE_OAUTH_TOKEN=\"$CRED\" ;;\n\
         \x20 esac\n\
         fi\n\
         exec \"{real_claude}\" \"$@\"\n"
    )
}

/// Merge our terminal-env keys into an existing `.vscode/settings.json` value
/// without clobbering the user's other settings. Prepends `bin_dir` to the
/// integrated-terminal PATH and sets CLAUDE_CONFIG_DIR. Returns the new JSON text.
pub fn merge_vscode_settings(existing: &str, bin_dir: &str, config_dir: &str) -> Result<String, String> {
    use serde_json::{Map, Value};
    let mut root: Value = if existing.trim().is_empty() {
        Value::Object(Map::new())
    } else {
        serde_json::from_str(existing).map_err(|e| format!("existing .vscode/settings.json is not valid JSON: {e}"))?
    };
    let obj = root.as_object_mut().ok_or("settings.json root is not an object")?;
    let env = obj.entry("terminal.integrated.env.osx".to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    let env = env.as_object_mut().ok_or("terminal.integrated.env.osx is not an object")?;
    env.insert("CLAUDE_CONFIG_DIR".to_string(), Value::String(config_dir.to_string()));
    env.insert("PATH".to_string(), Value::String(format!("{bin_dir}:${{env:PATH}}")));
    serde_json::to_string_pretty(&root).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_reads_keychain_and_execs_absolute() {
        let s = render_shim("work", "/cfg/work", "/opt/homebrew/bin/claude");
        assert!(s.contains("com.claudeprofiles.cli.work"));
        assert!(s.contains("export CLAUDE_CONFIG_DIR=\"/cfg/work\""));
        assert!(s.contains("sk-ant-api*) export ANTHROPIC_API_KEY="));
        assert!(s.contains("export CLAUDE_CODE_OAUTH_TOKEN="));
        // must exec the real binary by absolute path, NOT `command -v claude`
        assert!(s.trim_end().ends_with("exec \"/opt/homebrew/bin/claude\" \"$@\""));
        assert!(!s.contains("command -v claude"));
    }

    #[test]
    fn merge_into_empty_creates_keys() {
        let out = merge_vscode_settings("", "/p/work/bin", "/cfg/work").unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        let env = &v["terminal.integrated.env.osx"];
        assert_eq!(env["CLAUDE_CONFIG_DIR"], "/cfg/work");
        assert_eq!(env["PATH"], "/p/work/bin:${env:PATH}");
    }

    #[test]
    fn merge_preserves_existing_user_settings() {
        let existing = r#"{"editor.fontSize":14,"terminal.integrated.env.osx":{"FOO":"bar"}}"#;
        let out = merge_vscode_settings(existing, "/b", "/c").unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["editor.fontSize"], 14);                       // untouched
        assert_eq!(v["terminal.integrated.env.osx"]["FOO"], "bar"); // untouched
        assert_eq!(v["terminal.integrated.env.osx"]["CLAUDE_CONFIG_DIR"], "/c"); // added
    }

    #[test]
    fn merge_rejects_malformed_json() {
        assert!(merge_vscode_settings("{not json", "/b", "/c").is_err());
    }

    #[test]
    fn workspace_id_is_stable() {
        assert_eq!(workspace_id("cursor", "work", "/p"), workspace_id("cursor", "work", "/p"));
        assert_ne!(workspace_id("cursor", "work", "/p"), workspace_id("vscode", "work", "/p"));
    }
}
