// IDE integration: launch a CLI account inside a VS Code-family IDE at a project.
// A Claude Code account is chosen by the process env (CLAUDE_CONFIG_DIR + token).
// We make that env present in an IDE's integrated terminal without ever writing
// the secret into the project: seamless mode prepends a per-profile `bin/` dir
// (holding a `claude` shim that reads the Keychain) to the workspace terminal PATH.
use serde::{Deserialize, Serialize};

#[derive(Serialize, Clone)]
pub struct Ide {
    pub id: String,       // "vscode" | "cursor" | "windsurf" | "antigravity"
    pub name: String,     // display name
    pub cli_path: String, // resolved folder-opening CLI
}

#[derive(Serialize, Deserialize, Clone)]
pub struct Workspace {
    pub id: String,           // built via `workspace_id()` (SOH-delimited) — do NOT concatenate the fields naively
    pub account_slug: String,
    pub account_name: String,
    pub ide_id: String,
    pub ide_name: String,
    pub project_path: String,
    pub mode: String,         // "seamless" | "wrapper"
    pub created: Option<u64>,
    pub last_opened: Option<u64>,
}

/// Deterministic id for a binding (dedupes re-adds of the same triple).
pub fn workspace_id(ide_id: &str, account_slug: &str, project_path: &str) -> String {
    format!("{ide_id}\u{1}{account_slug}\u{1}{project_path}")
}

/// The `claude` shim body for a profile's private bin dir. Reads the per-slug
/// Keychain credential and branches by prefix; execs the REAL claude by ABSOLUTE
/// path (never `command -v claude`, which would find the shim and recurse).
/// Precondition: `slug` must be pre-slugified ([a-z0-9-], via platform::slugify) —
/// it is interpolated raw into the Keychain service/account strings.
/// If no credential is stored yet, no auth var is exported and claude still runs
/// (it will prompt to log in) — intentional.
/// Bash lines that read the profile's Keychain credential and export the right
/// auth env var by prefix. Shared by the `claude` shim and the terminal shell.
/// Reuses the single Keychain-service constant so it can't drift from cli.rs.
fn cred_export(slug: &str) -> String {
    let svc = format!("{}.{slug}", crate::cli::KEYCHAIN_PREFIX);
    format!(
        "CRED=\"$(security find-generic-password -w -s \"{svc}\" -a \"{slug}\" 2>/dev/null)\"\n\
         if [ -n \"$CRED\" ]; then\n\
         \x20 case \"$CRED\" in\n\
         \x20   sk-ant-api*) export ANTHROPIC_API_KEY=\"$CRED\" ;;\n\
         \x20   *)           export CLAUDE_CODE_OAUTH_TOKEN=\"$CRED\" ;;\n\
         \x20 esac\n\
         fi\n"
    )
}

pub fn render_shim(slug: &str, config_dir: &str, real_claude: &str) -> String {
    let cfg_e = crate::cli::sh_dq_escape(config_dir);
    let bin_e = crate::cli::sh_dq_escape(real_claude);
    format!(
        "#!/bin/bash\n\
         # Generated by Claude Profiles — `claude` shim for CLI account \"{slug}\".\n\
         export CLAUDE_CONFIG_DIR=\"{cfg_e}\"\n\
         {snippet}\
         exec \"{bin_e}\" \"$@\"\n",
        snippet = cred_export(slug)
    )
}

/// A workspace terminal shell: pre-loads the account env from the Keychain, then
/// hands off to your normal interactive login shell. Set as the VS Code default
/// terminal profile so EVERY terminal in the project is on the right account —
/// robust against login-shell PATH re-ordering (the token is a real env var, not
/// dependent on `claude` resolving to a shim). Execs `$SHELL` (the user's real
/// shell, inherited from the IDE — never this wrapper), so there is no recursion.
pub fn render_shell_wrapper(slug: &str, config_dir: &str) -> String {
    let cfg_e = crate::cli::sh_dq_escape(config_dir);
    format!(
        "#!/bin/bash\n\
         # Generated by Claude Profiles — terminal shell for CLI account \"{slug}\".\n\
         export CLAUDE_CONFIG_DIR=\"{cfg_e}\"\n\
         {snippet}\
         exec \"${{SHELL:-/bin/zsh}}\" -l -i\n",
        snippet = cred_export(slug)
    )
}

/// Merge our terminal-env keys into an existing `.vscode/settings.json` value
/// without clobbering the user's other settings. Prepends `bin_dir` to the
/// integrated-terminal PATH and sets CLAUDE_CONFIG_DIR. Returns the new JSON text.
/// Note: any pre-existing `terminal.integrated.env.osx.PATH` is replaced, not augmented.
pub fn merge_vscode_settings(existing: &str, bin_dir: &str, config_dir: &str) -> Result<String, String> {
    use serde_json::{Map, Value};
    let mut root: Value = if existing.trim().is_empty() {
        Value::Object(Map::new())
    } else {
        serde_json::from_str(existing).map_err(|e| format!("existing .vscode/settings.json is not valid JSON: {e}"))?
    };
    let obj = root.as_object_mut().ok_or("settings.json root is not an object")?;
    let env = obj.entry("terminal.integrated.env.osx".to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    let env = env.as_object_mut().ok_or("terminal.integrated.env.osx is not an object")?;
    env.insert("CLAUDE_CONFIG_DIR".to_string(), Value::String(config_dir.to_string()));
    env.insert("PATH".to_string(), Value::String(format!("{bin_dir}:${{env:PATH}}")));
    serde_json::to_string_pretty(&root).map_err(|e| e.to_string())
}

/// Merge a `folderOpen` task into an existing `.vscode/tasks.json` (preserving any
/// other tasks). Upserts by `label`. `command` is run as a process (not through a
/// shell) — pass the ABSOLUTE path to the profile's `claude` shim so it resolves
/// regardless of the login shell's PATH, and reveals a dedicated focused terminal.
pub fn merge_vscode_tasks(existing: &str, label: &str, command: &str) -> Result<String, String> {
    use serde_json::{json, Value};
    let mut root: Value = if existing.trim().is_empty() {
        json!({ "version": "2.0.0", "tasks": [] })
    } else {
        serde_json::from_str(existing).map_err(|e| format!("existing .vscode/tasks.json is not valid JSON: {e}"))?
    };
    let obj = root.as_object_mut().ok_or("tasks.json root is not an object")?;
    obj.entry("version".to_string()).or_insert_with(|| Value::String("2.0.0".into()));
    let tasks = obj.entry("tasks".to_string()).or_insert_with(|| Value::Array(vec![]));
    let arr = tasks.as_array_mut().ok_or("tasks.json 'tasks' is not an array")?;
    arr.retain(|t| t.get("label").and_then(|l| l.as_str()) != Some(label)); // upsert by label
    arr.push(json!({
        "label": label,
        "type": "process",
        "command": command,
        "presentation": { "reveal": "always", "panel": "dedicated", "focus": true, "clear": false },
        "runOptions": { "runOn": "folderOpen" },
        "problemMatcher": []
    }));
    serde_json::to_string_pretty(&root).map_err(|e| e.to_string())
}

/// Set the workspace's default integrated-terminal profile to a Claude shell that
/// pre-loads the account env, so terminals the user opens themselves are also on
/// the right account (not just the auto-opened one). Preserves other profiles.
pub fn merge_terminal_profile(existing: &str, profile_name: &str, shell_path: &str) -> Result<String, String> {
    use serde_json::{json, Map, Value};
    let mut root: Value = if existing.trim().is_empty() {
        Value::Object(Map::new())
    } else {
        serde_json::from_str(existing).map_err(|e| format!("settings.json is not valid JSON: {e}"))?
    };
    let obj = root.as_object_mut().ok_or("settings.json root is not an object")?;
    obj.insert("terminal.integrated.defaultProfile.osx".to_string(), Value::String(profile_name.to_string()));
    let profiles = obj.entry("terminal.integrated.profiles.osx".to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    let profiles = profiles.as_object_mut().ok_or("terminal.integrated.profiles.osx is not an object")?;
    profiles.insert(profile_name.to_string(), json!({ "path": shell_path }));
    serde_json::to_string_pretty(&root).map_err(|e| e.to_string())
}

#[cfg(target_os = "macos")]
mod imp {
    use super::*;
    use crate::platform::{home, run};
    use std::fs;
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;

    // Reuse the CLI account's config-dir root (per-slug dirs live here).
    pub fn cli_config_dir(slug: &str) -> PathBuf {
        home().join("Library/Application Support/ClaudeProfilesCLI").join(slug)
    }
    // Per-profile private bin dir holding the `claude` shim (prepended to workspace PATH).
    pub fn profile_bin_dir(slug: &str) -> PathBuf { cli_config_dir(slug).join("bin") }
    // Global dir for `claude-<slug>` wrappers (wrapper mode). Put on PATH by the user.
    pub fn wrapper_dir() -> PathBuf { home().join(".local/bin") }
    pub fn workspaces_file() -> PathBuf {
        home().join("Library/Application Support/ClaudeProfilesCLI/workspaces.json")
    }

    /// Absolute path to the real claude binary (mirrors cli.rs claude_bin()).
    pub fn real_claude() -> Option<PathBuf> {
        if let Ok(p) = std::env::var("CLAUDE_CLI_BIN") {
            let pb = PathBuf::from(p); if pb.is_file() { return Some(pb); }
        }
        let (ok, out) = run("which", &["claude"]);
        if ok { let p = PathBuf::from(out.trim()); if p.is_file() { return Some(p); } }
        for c in ["/opt/homebrew/bin/claude", "/usr/local/bin/claude",
                  "~/.local/bin/claude", "~/.claude/local/claude", "~/.bun/bin/claude"] {
            let pb = if let Some(r) = c.strip_prefix("~/") { home().join(r) } else { PathBuf::from(c) };
            if pb.is_file() { return Some(pb); }
        }
        None
    }

    /// Candidate VS Code-family IDEs: (id, display, [bundle-relative CLI paths to probe]).
    fn candidates() -> Vec<(&'static str, &'static str, Vec<PathBuf>)> {
        let apps = |rel: &str| vec![
            PathBuf::from("/Applications").join(rel),
            home().join("Applications").join(rel),
        ];
        let mut out = vec![];
        out.push(("vscode", "Visual Studio Code",
            apps("Visual Studio Code.app/Contents/Resources/app/bin/code")));
        out.push(("cursor", "Cursor",
            apps("Cursor.app/Contents/Resources/app/bin/cursor")));
        out.push(("windsurf", "Windsurf", {
            let mut v = apps("Windsurf.app/Contents/Resources/app/bin/windsurf");
            v.push(home().join(".codeium/windsurf/bin/windsurf"));
            v
        }));
        out.push(("antigravity", "Antigravity IDE",
            apps("Antigravity IDE.app/Contents/Resources/app/bin/antigravity-ide")));
        out
    }

    pub fn detect_ides() -> Vec<Ide> {
        let mut ides = vec![];
        for (id, name, paths) in candidates() {
            if let Some(p) = paths.into_iter().find(|p| p.is_file()) {
                ides.push(Ide { id: id.into(), name: name.into(), cli_path: p.display().to_string() });
            }
        }
        ides
    }

    pub fn ide_cli(ide_id: &str) -> Option<String> {
        detect_ides().into_iter().find(|i| i.id == ide_id).map(|i| i.cli_path)
    }

    fn write_exec(path: &PathBuf, body: &str) -> Result<(), String> {
        if let Some(dir) = path.parent() { fs::create_dir_all(dir).map_err(|e| e.to_string())?; }
        fs::write(path, body).map_err(|e| e.to_string())?;
        let mut perm = fs::metadata(path).map_err(|e| e.to_string())?.permissions();
        perm.set_mode(0o755);
        fs::set_permissions(path, perm).map_err(|e| e.to_string())
    }

    /// Install/refresh the per-profile `claude` shim and the global `claude-<slug>`
    /// wrapper (both share the shim body). Returns the profile bin dir.
    pub fn install_shims(slug: &str) -> Result<PathBuf, String> {
        let cfg = cli_config_dir(slug);
        let real = real_claude().ok_or("Claude Code CLI not found (install `claude`).")?;
        let body = render_shim(slug, &cfg.display().to_string(), &real.display().to_string());
        let bin = profile_bin_dir(slug);
        write_exec(&bin.join("claude"), &body)?;                       // seamless: on prepended PATH
        write_exec(&wrapper_dir().join(format!("claude-{slug}")), &body)?; // wrapper: global name
        // terminal shell for the workspace default profile (manual terminals too)
        let shell = render_shell_wrapper(slug, &cfg.display().to_string());
        write_exec(&bin.join("claude-shell"), &shell)?;
        Ok(bin)
    }

    pub fn load_workspaces() -> Vec<Workspace> {
        match fs::read_to_string(workspaces_file()) {
            Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
            Err(_) => vec![],
        }
    }
    pub fn save_workspaces(list: &[Workspace]) -> Result<(), String> {
        let f = workspaces_file();
        if let Some(d) = f.parent() { fs::create_dir_all(d).map_err(|e| e.to_string())?; }
        let s = serde_json::to_string_pretty(list).map_err(|e| e.to_string())?;
        fs::write(&f, s).map_err(|e| e.to_string())
    }
}

// ---- public API (macOS) --------------------------------------------------
#[cfg(target_os = "macos")]
pub fn list_ides() -> Vec<Ide> { imp::detect_ides() }

/// Native folder picker (osascript). Returns None if the user cancels.
#[cfg(target_os = "macos")]
pub fn pick_folder() -> Result<Option<String>, String> {
    let (ok, out) = crate::platform::run(
        "osascript", &["-e", "POSIX path of (choose folder with prompt \"Select a project folder\")"]);
    let s = out.trim().to_string();
    if ok && !s.is_empty() { Ok(Some(s)) }
    else if s.contains("User canceled") || s.is_empty() { Ok(None) }
    else { Err(s) }
}

/// Open `project_path` in the given IDE with `account` active in its integrated
/// terminal. `mode` = "seamless" (write .vscode/settings.json) or "wrapper"
/// (rely on the global claude-<slug>). Always (re)installs the shims first.
#[cfg(target_os = "macos")]
pub fn open_in_ide(account: &str, ide_id: &str, project_path: &str, mode: &str) -> Result<(), String> {
    use crate::platform::slugify;
    let slug = slugify(account);
    if slug.is_empty() { return Err("Invalid account name.".into()); }
    let proj = std::path::PathBuf::from(project_path);
    if !proj.is_dir() { return Err(format!("Not a folder: {project_path}")); }
    let cli = imp::ide_cli(ide_id).ok_or_else(|| format!("IDE not found: {ide_id}"))?;

    let bin = imp::install_shims(&slug)?; // both shim + wrapper

    if mode == "seamless" {
        let cfg = imp::cli_config_dir(&slug);
        let vscode = proj.join(".vscode");
        std::fs::create_dir_all(&vscode).map_err(|e| e.to_string())?;
        let sp = vscode.join("settings.json");
        let existing = std::fs::read_to_string(&sp).unwrap_or_default();
        let merged = merge_vscode_settings(&existing, &bin.display().to_string(), &cfg.display().to_string())?;
        // Default terminal profile → a shell that pre-loads this account's env, so
        // terminals the user opens themselves are on the right account too.
        let profile_name = format!("Claude ({account})");
        let shell_path = bin.join("claude-shell");
        let merged = merge_terminal_profile(&merged, &profile_name, &shell_path.display().to_string())?;
        std::fs::write(&sp, merged).map_err(|e| e.to_string())?;

        // Auto-open a Claude terminal on folder-open, running the shim by ABSOLUTE
        // path so the right account is used regardless of the login shell's PATH.
        let tp = vscode.join("tasks.json");
        let et = std::fs::read_to_string(&tp).unwrap_or_default();
        let label = format!("Claude Code — {account}");
        let shim = bin.join("claude");
        let tasks = merge_vscode_tasks(&et, &label, &shim.display().to_string())?;
        std::fs::write(&tp, tasks).map_err(|e| e.to_string())?;
    }

    // Open the folder (VS Code-family CLIs reuse a running instance; workspace
    // settings still apply per-window).
    let (ok, e) = crate::platform::run(&cli, &[project_path]);
    if ok { Ok(()) } else { Err(e) }
}

#[cfg(target_os = "macos")]
pub fn list_workspaces() -> Vec<Workspace> {
    let mut w = imp::load_workspaces();
    w.sort_by(|a, b| b.last_opened.cmp(&a.last_opened));
    w
}

#[cfg(target_os = "macos")]
pub fn save_workspace(account_slug: &str, account_name: &str, ide_id: &str, ide_name: &str,
                      project_path: &str, mode: &str, now: u64) -> Result<(), String> {
    let id = workspace_id(ide_id, account_slug, project_path);
    let mut list = imp::load_workspaces();
    if let Some(w) = list.iter_mut().find(|w| w.id == id) {
        w.last_opened = Some(now); w.mode = mode.to_string();
    } else {
        list.push(Workspace {
            id, account_slug: account_slug.into(), account_name: account_name.into(),
            ide_id: ide_id.into(), ide_name: ide_name.into(), project_path: project_path.into(),
            mode: mode.into(), created: Some(now), last_opened: Some(now),
        });
    }
    imp::save_workspaces(&list)
}

#[cfg(target_os = "macos")]
pub fn delete_workspace(id: &str) -> Result<(), String> {
    let mut list = imp::load_workspaces();
    list.retain(|w| w.id != id);
    imp::save_workspaces(&list)
}

/// Open a saved workspace by id (re-applies activation + launches), stamping
/// last_opened with `now`.
#[cfg(target_os = "macos")]
pub fn open_workspace(id: &str, now: u64) -> Result<(), String> {
    let list = imp::load_workspaces();
    let w = list.into_iter().find(|w| w.id == id).ok_or("No such workspace")?;
    open_in_ide(&w.account_name, &w.ide_id, &w.project_path, &w.mode)?;
    save_workspace(&w.account_slug, &w.account_name, &w.ide_id, &w.ide_name, &w.project_path, &w.mode, now)
}

// ---- non-macOS stubs -----------------------------------------------------
#[cfg(not(target_os = "macos"))]
const NOT_YET: &str = "IDE workspaces are macOS-only for now.";
#[cfg(not(target_os = "macos"))]
pub fn list_ides() -> Vec<Ide> { vec![] }
#[cfg(not(target_os = "macos"))]
pub fn pick_folder() -> Result<Option<String>, String> { Err(NOT_YET.into()) }
#[cfg(not(target_os = "macos"))]
pub fn open_in_ide(_a: &str, _i: &str, _p: &str, _m: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(target_os = "macos"))]
pub fn list_workspaces() -> Vec<Workspace> { vec![] }
#[cfg(not(target_os = "macos"))]
pub fn save_workspace(_a: &str, _b: &str, _c: &str, _d: &str, _e: &str, _f: &str, _n: u64) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(target_os = "macos"))]
pub fn delete_workspace(_id: &str) -> Result<(), String> { Err(NOT_YET.into()) }
#[cfg(not(target_os = "macos"))]
pub fn open_workspace(_id: &str, _n: u64) -> Result<(), String> { Err(NOT_YET.into()) }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_reads_keychain_and_execs_absolute() {
        let s = render_shim("work", "/cfg/work", "/opt/homebrew/bin/claude");
        assert!(s.contains("com.claudeprofiles.cli.work"));
        assert!(s.contains("export CLAUDE_CONFIG_DIR=\"/cfg/work\""));
        assert!(s.contains("sk-ant-api*) export ANTHROPIC_API_KEY="));
        assert!(s.contains("export CLAUDE_CODE_OAUTH_TOKEN="));
        // must exec the real binary by absolute path, NOT `command -v claude`
        assert!(s.trim_end().ends_with("exec \"/opt/homebrew/bin/claude\" \"$@\""));
        assert!(!s.contains("command -v claude"));
    }

    #[test]
    fn merge_into_empty_creates_keys() {
        let out = merge_vscode_settings("", "/p/work/bin", "/cfg/work").unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        let env = &v["terminal.integrated.env.osx"];
        assert_eq!(env["CLAUDE_CONFIG_DIR"], "/cfg/work");
        assert_eq!(env["PATH"], "/p/work/bin:${env:PATH}");
    }

    #[test]
    fn merge_preserves_existing_user_settings() {
        let existing = r#"{"editor.fontSize":14,"terminal.integrated.env.osx":{"FOO":"bar"}}"#;
        let out = merge_vscode_settings(existing, "/b", "/c").unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["editor.fontSize"], 14);                       // untouched
        assert_eq!(v["terminal.integrated.env.osx"]["FOO"], "bar"); // untouched
        assert_eq!(v["terminal.integrated.env.osx"]["CLAUDE_CONFIG_DIR"], "/c"); // added
    }

    #[test]
    fn merge_rejects_malformed_json() {
        assert!(merge_vscode_settings("{not json", "/b", "/c").is_err());
    }

    #[test]
    fn workspace_id_is_stable() {
        assert_eq!(workspace_id("cursor", "work", "/p"), workspace_id("cursor", "work", "/p"));
        assert_ne!(workspace_id("cursor", "work", "/p"), workspace_id("vscode", "work", "/p"));
    }

    #[test]
    fn tasks_merge_creates_folderopen_task() {
        let out = merge_vscode_tasks("", "Claude Code — Work", "/cfg/work/bin/claude").unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["version"], "2.0.0");
        let t = &v["tasks"][0];
        assert_eq!(t["command"], "/cfg/work/bin/claude");
        assert_eq!(t["runOptions"]["runOn"], "folderOpen");
        assert_eq!(t["type"], "process");
    }

    #[test]
    fn tasks_merge_upserts_and_preserves_others() {
        let existing = r#"{"version":"2.0.0","tasks":[{"label":"build","type":"shell","command":"make"},{"label":"Claude Code — Work","command":"/old"}]}"#;
        let out = merge_vscode_tasks(existing, "Claude Code — Work", "/new/claude").unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        let arr = v["tasks"].as_array().unwrap();
        assert_eq!(arr.len(), 2); // build preserved, our task upserted (not duplicated)
        assert!(arr.iter().any(|t| t["label"] == "build" && t["command"] == "make"));
        let ours: Vec<_> = arr.iter().filter(|t| t["label"] == "Claude Code — Work").collect();
        assert_eq!(ours.len(), 1);
        assert_eq!(ours[0]["command"], "/new/claude");
    }

    #[test]
    fn tasks_merge_rejects_malformed() {
        assert!(merge_vscode_tasks("{bad", "L", "/c").is_err());
    }

    #[test]
    fn shell_wrapper_sets_env_and_execs_real_shell() {
        let s = render_shell_wrapper("work", "/cfg/work");
        assert!(s.contains("export CLAUDE_CONFIG_DIR=\"/cfg/work\""));
        assert!(s.contains("com.claudeprofiles.cli.work"));
        assert!(s.contains("sk-ant-api*) export ANTHROPIC_API_KEY="));
        // hands off to the user's real shell, not itself (no recursion)
        assert!(s.trim_end().ends_with("exec \"${SHELL:-/bin/zsh}\" -l -i"));
    }

    #[test]
    fn terminal_profile_sets_default_and_preserves_others() {
        let existing = r#"{"editor.fontSize":13,"terminal.integrated.profiles.osx":{"bash":{"path":"/bin/bash"}}}"#;
        let out = merge_terminal_profile(existing, "Claude (Work)", "/cfg/work/bin/claude-shell").unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["editor.fontSize"], 13);                                   // untouched
        assert_eq!(v["terminal.integrated.defaultProfile.osx"], "Claude (Work)");
        assert_eq!(v["terminal.integrated.profiles.osx"]["bash"]["path"], "/bin/bash"); // preserved
        assert_eq!(v["terminal.integrated.profiles.osx"]["Claude (Work)"]["path"], "/cfg/work/bin/claude-shell");
    }

    #[test]
    fn workspace_id_delimiter_avoids_collisions() {
        assert_ne!(workspace_id("ide", "wo", "rk/p"), workspace_id("ide", "work", "/p"));
    }

    #[test]
    fn merge_rejects_non_object_root() {
        assert!(merge_vscode_settings("[1,2,3]", "/b", "/c").is_err());
    }

    #[test]
    fn merge_rejects_non_object_env() {
        assert!(merge_vscode_settings(r#"{"terminal.integrated.env.osx":"oops"}"#, "/b", "/c").is_err());
    }

    #[test]
    fn shim_escapes_shell_metachars_in_paths() {
        let s = render_shim("work", "/cfg/$X`id`", "/bin/claude");
        assert!(s.contains("export CLAUDE_CONFIG_DIR=\"/cfg/\\$X\\`id\\`\""));
    }
}
